// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGfO7TjYSSY6eVDEIzYB2TkyZ7g4ituko',
    appId: '1:435617791733:web:3de9301bea8d6345490fbc',
    messagingSenderId: '435617791733',
    projectId: 'bhashini-976ed',
    authDomain: 'bhashini-976ed.firebaseapp.com',
    storageBucket: 'bhashini-976ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-DuaUw7xnFaB0t-gdcxAqOveiDyQmUg',
    appId: '1:435617791733:android:91fdc77be1e263e7490fbc',
    messagingSenderId: '435617791733',
    projectId: 'bhashini-976ed',
    storageBucket: 'bhashini-976ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcFMSyNXToHsnkwG8V66ZDVFYZ4bvAld4',
    appId: '1:435617791733:ios:0ab6a39b25801431490fbc',
    messagingSenderId: '435617791733',
    projectId: 'bhashini-976ed',
    storageBucket: 'bhashini-976ed.appspot.com',
    iosBundleId: 'com.example.bhashini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcFMSyNXToHsnkwG8V66ZDVFYZ4bvAld4',
    appId: '1:435617791733:ios:5e6f25193c2621d6490fbc',
    messagingSenderId: '435617791733',
    projectId: 'bhashini-976ed',
    storageBucket: 'bhashini-976ed.appspot.com',
    iosBundleId: 'com.example.bhashini.RunnerTests',
  );
}
